# Generated by Django 2.2.7 on 2020-04-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Характеристика')),
            ],
        ),
        migrations.CreateModel(
            name='CharValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
            ],
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.CharName'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.CharValue'),
        ),
    ]
