# Generated by Django 2.2.7 on 2020-04-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200423_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
        migrations.DeleteModel(
            name='CharName',
        ),
        migrations.DeleteModel(
            name='CharValue',
        ),
    ]
