# Generated by Django 2.2.7 on 2020-04-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200423_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(auto_now=True, verbose_name='Опубликовано'),
        ),
    ]
