# Generated by Django 3.0.5 on 2020-06-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200505_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='filter_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Назва для фільтру'),
        ),
    ]
