# Generated by Django 3.0.5 on 2020-05-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200505_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Прийнятий', 'Прийнятий'), ('В обробці', 'В обробці'), ('Виконаний', 'Виконаний'), ('Відмінений', 'Відмінений')], default='Прийнятий', max_length=10, verbose_name='Статус'),
        ),
    ]
